version: '3.8'
services:
  api:
    image: mixola/hosting:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:25000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
  pg:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#        - pg_data:/var/lib/postgresql/data
#    ports:
#        - '${POSTGRES_PORT:-5432}:5432'
#    healthcheck:
#        test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
#        interval: 3s
#        timeout: 3s
#        retries: 3


