version: '3.8'
services:
  api:
    image: mixola/hosting:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:25000"
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: mixola/hosting:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: flask db upgrade

  db:
    image: postgres:14.6-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - pg_data:/var/lib/postgresql/data
    ports:
        - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 3s
        timeout: 3s
        retries: 3

