version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mixola/hosting
    ports:
      - "80:25000"
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build: .
    image: mixola/hosting
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - .env
    command: flask db upgrade

  pg:
    image: postgres:14.6-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - pg_data:/var/lib/postgresql/data
    ports:
        - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
        test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
        interval: 3s
        timeout: 3s
        retries: 3

volumes:
  pg_data: