version: '3.8'
services:
  api:
    image: mixola/hosting:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8080:5000"
    environment:
      - DB_PASSWORD=db_password
      - DB_USER=db_user
      - DB_NAME=db_name
  pg:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name



